nav:
  - 11-indice.md
  - 11.1-vision-general.md
  - 11.2-lab0-federado-puro.md
  - 11.3-lab1-patron-de-ficheros.md
  - 11.4-lab2-el-contenedor.md
  - 11.5-lab3-ocean-node.md
  - 11.6-contrato-c2d.md
  - 11.7-troubleshooting.md
  - 11.8-donde-encaja-flower.md
  - 11.9-recursos-y-glosario.md
  - 11.10-como-esta-montado.md
